/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    id("com.fussionlabs.gradle.go-plugin") version("0.5.2")
}

version = "0.0.1"
val moduleName = "github.com/dm0275/weather-cli"

go {
    os = listOf("darwin")
    arch = listOf("arm64")
    ldFlags = mapOf("github.com/dm0275/weather-cli/pkg/version.version" to "$version",
        "github.com/dm0275/weather-cli/pkg/version.os" to "darwin",
        "github.com/dm0275/weather-cli/pkg/version.arch" to "arm64")
}