/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    id("base")
}

 tasks.register("goBuildDarwin") {
     doLast {
         val outputDir: File = layout.buildDirectory.asFile.get()
         // Create build dir
         mkdir(outputDir)

         exec {
             executable = "go"
             args = listOf("build", "-o", outputDir.path, projectDir.path)
         }
     }
 }

tasks.getByPath("build").dependsOn("goBuildDarwin")