/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    id("base")
}

version = "0.0.1"
val moduleName = "github.com/dm0275/weather-cli"

tasks.register("goBuildDarwin") {
    group = "build"
    doLast {
        var flags = ""
        val goBinary = "go"
        val ldFlags = mapOf("$moduleName/pkg/version.version" to version,
                "$moduleName/pkg/version.os" to "darwin",
                "$moduleName/pkg/version.arch" to "arm64")
        val outputDir: File = layout.buildDirectory.asFile.get()

        // Create build dir
        mkdir(outputDir)

        // Setup args
        var goTaskArgs = "build -a "

        // Configure output dir
        goTaskArgs += "-o ${outputDir.path} "

        // Setup ld flags
        ldFlags.forEach { (key, value) ->
            flags += "-X $key=$value "
        }
        goTaskArgs += "-ldflags='$flags' "

        // Configure project path
        goTaskArgs += projectDir.path

        exec {
            executable = "sh"
            args = mutableListOf("-c", "$goBinary $goTaskArgs")
        }
    }
}

tasks.getByPath("build").dependsOn("goBuildDarwin")